# Generated by Django 5.0.3 on 2024-04-19 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facemeet', '0002_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='participant',
            name='mood_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('requester', 'receiver')},
        ),
        migrations.CreateModel(
            name='ExpressionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expression_scores', to='Facemeet.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('text', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_transcriptions', to='Facemeet.meeting')),
            ],
        ),
    ]
