# Generated by Django 5.0.3 on 2024-04-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facemeet', '0004_meeting_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='atmosphere_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='expression_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='0d636861420e419bbb7c25bde5119493', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_link',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
