# Generated by Django 5.0.3 on 2024-04-22 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facemeet', '0005_alter_meeting_atmosphere_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings', through='Facemeet.Participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expressionscore',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expressionscore',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='209f2a03742e4ec58991e618072413c8', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='join_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='leave_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='voicetranscription',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='voicetranscription',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
