# Generated by Django 5.0.3 on 2024-04-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facemeet', '0007_alter_meeting_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='a0cd6b11c37644cfa3b8c910a227b6f4', max_length=100),
        ),
    ]
