# Generated by Django 5.0.3 on 2024-05-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facemeet', '0009_alter_meeting_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='participant_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='a8e96f7694a642edb2bd0fff5df1ada7', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'meeting')},
        ),
    ]
