# Generated by Django 5.0.3 on 2024-05-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facemeet', '0010_meeting_participant_count_alter_meeting_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='0b249f9995cf436da1a9c841516c55aa', max_length=100),
        ),
    ]
