# Generated by Django 5.0.3 on 2024-05-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facemeet', '0011_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='participant_count',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='d31147581d0c4152aaa6ecc783730ac4', max_length=100),
        ),
    ]
